export const AllMethods: string[] = ['get', 'post', 'options', 'put', 'delete', 'patch', 'head'];

export const SortList = ['requestQueryCode', 'requestHeaderCode', 'requestCookieCode', 'requestBodyCode', 'responsesCode', 'requestFuncTypeCode', 'requestUrl'];

export const NotModifyCode = `/* tslint:disable */
/**
* This file was automatically generated by openapi-gen-typescript.
* DO NOT MODIFY IT BY HAND.
*/\n`

export enum ETemplateCode {
  RequestQueryCode = 'requestQueryCode',
  RequestHeaderCode = 'requestHeaderCode',
  RequestCookieCode = 'requestCookieCode',
  RequestBodyCode = 'requestBodyCode',
  ResponsesCode = 'responsesCode',
  RequestFuncTypeCode = 'requestFuncTypeCode',
  RequestUrl = 'requestUrl',
}